### ISSUE TITLE
Cannot compile code

### ISSUE THREAD

**Issue by msegala** [andreasjansson/fast-shapelets#1]
I am trying to run the code by compiling with:
> gcc FastShapelet.cpp -std=c++11 -stdlib=libc++ -o out

However, I keep getting the error
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea on how to get the code to run?

**Comment by andreasjansson** [comment]
Sorry, I just mirrored it from http://alumni.cs.ucr.edu/~rakthant/FastShapelet/, I can't remember what I did to make it build. To be honest, I forgot that I even had this repo. I'll probably just delete it since it's more likely the code on that website is kept better up to date.
